# This TOML configuration adds configurations for UICR that are currently
# unable to be set through devicetree.

[grtc_cc_secure_0]
CC_6 = "NonSecure"
CC_7 = "NonSecure"

[initnsvtor_0]
INITNSVTOR = 0x0e099000

[gpio_own_5]
PIN_0 = "Own"
PIN_2 = "Own"

[gpio_secure_5]
PIN_0 = "NonSecure"
PIN_2 = "NonSecure"

[gpiote_ch_secure_0]
CH_0 = "NonSecure"
CH_2 = "NonSecure"
CH_4 = "NonSecure"
CH_5 = "NonSecure"
CH_6 = "NonSecure"
CH_7 = "NonSecure"
