# This TOML configuration adds configurations for UICR that are currently
# unable to be set through devicetree.

[gpio_own_5]
PIN_1 = "Own"

[gpio_secure_5]
PIN_1 = "NonSecure"

[gpio_own_0]
PIN_9 = "Own"

[gpio_secure_0]
PIN_9 = "NonSecure"

[gpiote_ch_secure_0]
CH_1 = "NonSecure"
CH_3 = "NonSecure"
