CONFIG_NRF_802154_ENCRYPTION=n
CONFIG_NRF_802154_TEMPERATURE_UPDATE=n
CONFIG_NRF_802154_SOURCE_INTERNAL=y

CONFIG_HEAP_MEM_POOL_SIZE=4096

CONFIG_NRF_IRQ_OFFLOAD=y
CONFIG_EGU_NRFX_DRIVER=y
CONFIG_NRFX_EGU020=y

CONFIG_MBOX=y
CONFIG_IPC_SERVICE=y
CONFIG_IPC_SERVICE_BACKEND_RPMSG=y
CONFIG_MBOX_NRFX_IDS=y

CONFIG_NRF_REGTOOL_TOML_CONFIG_FILES="boards/nrf54h20dk_nrf54h20_cpurad.toml"

# Due to timming limitations on FPGA board it is needed to increase ACK timeout for ieee802154
# This timeout is important to work with OpenThread.
CONFIG_NRF_802154_ACK_TIMEOUT_CUSTOM_US=2000

# For now GRTC is not compatible with radio driver, so it is needed to disable GRTC timer
# and use SYSTICK.
CONFIG_CORTEX_M_SYSTICK=y
CONFIG_NRF_GRTC_TIMER=n
