/*$$$LICENCE_NORDIC_STANDARD<2020>$$$*/

#ifndef NRFX_CONFIG_HALTIUM_NETWORK_H__
#define NRFX_CONFIG_HALTIUM_NETWORK_H__

#define EGU020_CH_NUM  4
#define DPPI_CH_NUM    16
#define DPPI_GROUP_NUM 2
#define DPPI_PRESENT   1

#endif // NRFX_CONFIG_HALTIUM_NETWORK_H__
